# Generated by Django 4.2.6 on 2023-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyincome',
            unique_together={('courier', 'date')},
        ),
    ]
