# Generated by Django 4.2.6 on 2023-10-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0002_tripincome_reward_forfeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Value')),
                ('date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_incomes', to='courier_income.courier', verbose_name='Courier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
