# Generated by Django 4.2.6 on 2023-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0003_dailyincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyincome',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='dailyincome',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='forfeit',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='tripincome',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Value'),
        ),
    ]
