# Generated by Django 4.2.6 on 2023-10-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_income', '0003_alter_dailyincome_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('start_date', models.DateField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_incomes', to='courier_income.courier', verbose_name='Courier')),
            ],
            options={
                'unique_together': {('courier', 'start_date')},
            },
        ),
    ]
